name: Rust CI

on:
    push:
        branches:
            - main
    pull_request:
    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: dtolnay/rust-toolchain@stable
            - uses: r7kamura/rust-problem-matchers@v1.5.0
            - uses: actions/cache@v4
              continue-on-error: false
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                restore-keys: ${{ runner.os }}-cargo-

            - run: cargo fmt --all -- --check
            - run: cargo check
            # - run: cargo clippy --tests -- -Dclippy::all
            - run: cargo test